### ISSUE TITLE
no data 

### ISSUE THREAD

**Issue by oferchichi** [LouisPlisso/pytomo#1]
Hello, after using pytomo in version 3.0.5 most of the field in database are not generated  I am not be able to have results in the db find in attach
![pytomo](https://f.cloud.github.com/assets/889248/1939288/f76be4fe-7f5e-11e3-8428-eec28117ddc4.JPG)

**Comment by LouisPlisso** [comment]
I'm updating the issue list, please give the command line invocation
it could be related to https://github.com/LouisPlisso/pytomo/issues/2

**Comment by LouisPlisso** [comment]
I expect the fix for this issue is working:
https://github.com/LouisPlisso/pytomo/issues/6

closing as duplicate
